apiVersion: v2
name: romm
description: A Helm chart for RomM - Beautiful, powerful, self-hosted ROM manager
type: application
version: 1.0.1
appVersion: "4.5.0"
icon: https://romm.app/images/blocks/logos/romm-light.svg
keywords:
  - romm
  - emulation
  - retrogaming
  - rom-manager
home: https://romm.app/
sources:
  - https://github.com/rommapp/romm
maintainers:
  - name: HenriqZimer
    email: henriqzimer@users.noreply.github.com
    url: https://github.com/HenriqZimer
