{{- if and .Values.secrets.enabled .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mariadb.secretName | default "romm-database-credentials" }}
  labels:
    {{- include "romm.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.data }}
  {{- if hasPrefix "MYSQL_" $key }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- range $key, $val := .Values.secrets.data }}
  {{- if hasPrefix "DB_" $key }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
