apiVersion: v1
kind: Service
metadata:
  name: {{ include "romm.fullname" . }}
  labels:
    {{- include "romm.labels" . | nindent 4 }}
    app.kubernetes.io/component: romm
    {{- with .Values.romm.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.romm.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.romm.service.type }}
  ports:
    - port: {{ .Values.romm.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.romm.service.portName }}
  selector:
    {{- include "romm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: romm
