{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "romm.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ printf "%s-db" (include "romm.fullname" .) | b64enc | quote }}
  {{- range $key, $val := .Values.secrets.data }}
  {{- if not (hasPrefix "MYSQL_" $key) }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
